/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fiches;

import static Fiches.Page_accueil.DOSS_IMAGES;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author laumu
 */
public class page_regles extends javax.swing.JDialog {
    private Image img;
    

    /**
     * Creates new form page_regles
     */
    public page_regles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        regles.setEnabled(false);
        Toolkit t=Toolkit.getDefaultToolkit();
        // création d'une icône et assignation au label
        img=t.getImage(DOSS_IMAGES+"logo.png");
        img=img.getScaledInstance(logo.getWidth(),logo.getHeight(), Image.SCALE_DEFAULT);    
        logo.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        regles = new javax.swing.JTextArea();
        b_retour = new javax.swing.JButton();
        l_regles = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setTitle("Règles du Jeu");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        regles.setEditable(false);
        regles.setBackground(new java.awt.Color(255, 255, 255));
        regles.setColumns(20);
        regles.setForeground(new java.awt.Color(0, 0, 0));
        regles.setRows(5);
        regles.setText("\nLes règles du jeu sont simples:\n\nVotre objectif? Gagner un maximum de points en faisant les alignements les plus longs possibles.\nPour qu'un alignement soit validé, il faut au moins aligner 5 billes de la même couleur. \nPour cela, cliquez sur la bille que vous voulez déplacer, puis sur la case vide dans laquelle vous souhaitez déplacer cette bille.\nAttention, vous ne pouvez déplacer une bille dans une case vide que s'il existe un chemin entre ces deux cases. \n\nLes billes classiques sont de 7 couleurs différentes: Noire, Violette, Bleue, Verte, Jaune, Rouge et Rose.\nMais pour pimenter le jeu, il existe aussi des billes spéciales, les billes bicolores ainsi que les billes fusée et arc en ciel.\nComme leur nom l'indique, les billes bicolores possèdent 2 couleurs à la fois. Si une bille est verte et jaune, elle peut participer\nà un alignement de billes vertes ou à un alignement de billes jaunes. \nLes billes fusée s'alignent avec n'importe quelle couleur et quand elles font partie d'un alignement, toutes les billes de la couleur de \nl'alignement disparaissent de la grille.\nLes billes arc-en-ciel ont les mêmes propriétés qu'une bille classique mais sont de n'importe quelle couleur. \n\nLe jeu se décline en trois niveaux de difficulté:\n- facile (1 bille apparaît à chaque déplacement)\n- moyen (2 billes apparaissent à chaque déplacement)\n- difficile (4 billes apparaissent à chaque déplacement).\n\nQuant aux points, ils se gagnent de la manière suivante:\n5 billes = 30 points\n6 billes = 50 points\n7 billes = 70 points\n8 billes = 90 points\n9 billes = 110 points\n\nQuand il n'y a plus de case vide, le jeu s'arrête.\n\nAmusez-vous bien !\n");
        jScrollPane1.setViewportView(regles);

        b_retour.setBackground(new java.awt.Color(150, 20, 140));
        b_retour.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_retour.setForeground(new java.awt.Color(255, 255, 255));
        b_retour.setText("Retour");
        b_retour.setBorder(null);
        b_retour.setBorderPainted(false);
        b_retour.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_retourActionPerformed(evt);
            }
        });

        l_regles.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        l_regles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_regles.setText("LES REGLES DU JEU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)
                        .addComponent(l_regles, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 94, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(b_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_regles, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(b_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_retourActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ((Page_accueil)getParent()).getPage_jeu().setVisible(true);
    }//GEN-LAST:event_b_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page_regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page_regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page_regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page_regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                page_regles dialog = new page_regles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_retour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_regles;
    private javax.swing.JLabel logo;
    private javax.swing.JTextArea regles;
    // End of variables declaration//GEN-END:variables
}
