/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fiches;

import static Fiches.Page_accueil.DOSS_IMAGES;
import java.awt.Image;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import projet.jeu.cinq.Jeu;
import projet.jeu.cinq.Joueur;

/**
 *
 * @author laumu
 */
public class page_meilleurs_scores extends javax.swing.JDialog {

    private Joueur joueur;
    private JTable tabBestScore = new JTable();
    private ArrayList<Joueur> liste_joueurs = new ArrayList<Joueur>();
    private Jeu monJeu;
    private Image img1;
    private Image img2;
    private Image img3;
    private LocalDate date;

    /**
     * Creates new form page_meilleurs_scores
     */
    public page_meilleurs_scores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        liste_joueurs = ((Page_accueil) getParent()).getListeJoueurs();// On récupère 
        //la liste contenant les joueurs de la page d'accueil
        Toolkit t = Toolkit.getDefaultToolkit();
        // création d'une icône et assignation au label
        img1 = t.getImage(DOSS_IMAGES + "medaille1.png");
        img1 = img1.getScaledInstance(icon1.getWidth(), icon1.getHeight(), Image.SCALE_DEFAULT);
        icon1.setIcon(new ImageIcon(img1));

        // création d'une icône et assignation au label
        img2 = t.getImage(DOSS_IMAGES + "medaille2.png");
        img2 = img2.getScaledInstance(icon2.getWidth(), icon2.getHeight(), Image.SCALE_DEFAULT);
        icon2.setIcon(new ImageIcon(img2));

        // création d'une icône et assignation au label
        img3 = t.getImage(DOSS_IMAGES + "medaille3.png");
        img3 = img3.getScaledInstance(icon3.getWidth(), icon3.getHeight(), Image.SCALE_DEFAULT);
        icon3.setIcon(new ImageIcon(img3));
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_scores = new javax.swing.JLabel();
        b_retour = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabScores = new javax.swing.JTable();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Meilleurs Scores");

        l_scores.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        l_scores.setForeground(new java.awt.Color(0, 0, 0));
        l_scores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_scores.setText("MEILLEURS SCORES");

        b_retour.setBackground(new java.awt.Color(233, 173, 15));
        b_retour.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_retour.setForeground(new java.awt.Color(255, 255, 255));
        b_retour.setText("Retour");
        b_retour.setBorder(null);
        b_retour.setBorderPainted(false);
        b_retour.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_retourActionPerformed(evt);
            }
        });

        tabScores.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tabScores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "        Pseudo", "          Score", "           Date", "          Niveau"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabScores.setAlignmentX(2.0F);
        tabScores.setAlignmentY(2.0F);
        tabScores.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        tabScores.setDragEnabled(true);
        tabScores.setName(""); // NOI18N
        tabScores.setRowHeight(30);
        tabScores.setSelectionBackground(new java.awt.Color(255, 204, 153));
        tabScores.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabScores.setShowVerticalLines(true);
        jScrollPane2.setViewportView(tabScores);

        icon1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_scores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(l_scores, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icon3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addComponent(b_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_retourActionPerformed
        // TODO add your handling code here:
        //permet de retourner à la page de jeu
        this.setVisible(false);
        ((Page_accueil) getParent()).getPage_jeu().setVisible(true);
    }//GEN-LAST:event_b_retourActionPerformed
    public void init() {
        //permet d'initialiser le tableau de scores dans la fiche meilleurs_scores
        for (int i = 0; i < liste_joueurs.size(); i++) {
            joueur = liste_joueurs.get(i);
            tabScores.setValueAt(joueur.getPseudo(), i, 0);// on ajoute le pseudo sur la i-ème ligne dans la première colonne
            tabScores.setValueAt(joueur.getScore(), i, 1);// on ajoute le score sur la i-ème ligne dans la deuxième colonne
            tabScores.setValueAt(joueur.getDate(), i,2);// on ajoute la date sur la i-ème ligne dans la troisième colonne
            tabScores.setValueAt(joueur.getNiveau(), i,3);// on ajoute le  niveau sur la i-ème ligne et la dernière colonne
            
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page_meilleurs_scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page_meilleurs_scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page_meilleurs_scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page_meilleurs_scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                page_meilleurs_scores dialog = new page_meilleurs_scores(new javax.swing.JFrame(), true);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_retour;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l_scores;
    private javax.swing.JTable tabScores;
    // End of variables declaration//GEN-END:variables
}
