package Fiches;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import projet.jeu.cinq.Joueur;

/**
 *
 * @author laumu
 */
public class Page_accueil extends javax.swing.JFrame {
    private page_jeu page_jeu;
    private page_regles page_regles;
    private page_meilleurs_scores meilleurs_scores;
    private LocalDate date=LocalDate.now();
    private String niveau;
    private Joueur joueur=new Joueur("",0, date, niveau);
    private Image img;
    private ArrayList<Joueur> liste_joueurs = new ArrayList<>(); 
    public static final String DOSS_IMAGES="src/Images/";
    private int n; // définit le niveau de jeu choisi par le joueur
        
    /**
     * Creates new form Page_accueil
     */
    public Page_accueil() throws IOException {
        initComponents();
        //initialisation des pages
        page_regles=new page_regles(this,false);
        meilleurs_scores= new page_meilleurs_scores(this,false);
        page_jeu=new page_jeu(this,false);
        b_debut_jeu.setEnabled(false);// le bouton de début de jeu n'est pas cliquable tant que le joueur ne rentre son pseudo
        Toolkit t=Toolkit.getDefaultToolkit();            
        // création d'une icône et assignation au label
        img=t.getImage(DOSS_IMAGES+"22 EPF Pastille Logo.png");
        img=img.getScaledInstance(logo.getWidth(),logo.getHeight(), Image.SCALE_DEFAULT);
        logo.setIcon(new ImageIcon(img));
    }

    public page_jeu getPage_jeu() {
        return page_jeu;
    }

    public int getN() {
        return n;
    }

    public page_regles getPage_regles() {
        return page_regles;
    }
    
    public page_meilleurs_scores getMeilleurs_scores(){
        return meilleurs_scores;
    }

    public Joueur getJoueur() {
        return joueur;
    }
    
    public ArrayList<Joueur> getListeJoueurs(){
        return liste_joueurs;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_niveau = new javax.swing.ButtonGroup();
        b_debut_jeu = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        accueilPanel = new javax.swing.JPanel();
        qPseudo = new javax.swing.JLabel();
        entree_pseudo = new javax.swing.JTextField();
        bienvenue = new javax.swing.JLabel();
        niveauPanel = new javax.swing.JPanel();
        b_facile = new javax.swing.JRadioButton();
        b_moyen = new javax.swing.JRadioButton();
        b_difficile = new javax.swing.JRadioButton();
        l_niveau = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        projet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");
        setBackground(new java.awt.Color(255, 0, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        b_debut_jeu.setBackground(new java.awt.Color(150, 20, 140));
        b_debut_jeu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b_debut_jeu.setForeground(new java.awt.Color(255, 255, 255));
        b_debut_jeu.setText("Appuyer pour lancer une partie!");
        b_debut_jeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_debut_jeuActionPerformed(evt);
            }
        });

        logo.setMaximumSize(new java.awt.Dimension(500, 500));
        logo.setMinimumSize(new java.awt.Dimension(500, 500));
        logo.setPreferredSize(new java.awt.Dimension(500, 500));

        qPseudo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        qPseudo.setForeground(new java.awt.Color(187, 22, 64));
        qPseudo.setText("Quel est votre pseudo?");

        entree_pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree_pseudoActionPerformed(evt);
            }
        });

        bienvenue.setBackground(new java.awt.Color(255, 0, 204));
        bienvenue.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        bienvenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenue.setText("BIENVENUE !!");

        b_niveau.add(b_facile);
        b_facile.setSelected(true);
        b_facile.setText("Facile");

        b_niveau.add(b_moyen);
        b_moyen.setText("Moyen");

        b_niveau.add(b_difficile);
        b_difficile.setText("Difficile");

        javax.swing.GroupLayout niveauPanelLayout = new javax.swing.GroupLayout(niveauPanel);
        niveauPanel.setLayout(niveauPanelLayout);
        niveauPanelLayout.setHorizontalGroup(
            niveauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(niveauPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(niveauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_moyen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_difficile, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, niveauPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_facile, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        niveauPanelLayout.setVerticalGroup(
            niveauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(niveauPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_facile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_moyen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_difficile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        l_niveau.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        l_niveau.setForeground(new java.awt.Color(187, 22, 64));
        l_niveau.setText("Quel niveau de difficulté  choississez-vous?");

        javax.swing.GroupLayout accueilPanelLayout = new javax.swing.GroupLayout(accueilPanel);
        accueilPanel.setLayout(accueilPanelLayout);
        accueilPanelLayout.setHorizontalGroup(
            accueilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accueilPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accueilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accueilPanelLayout.createSequentialGroup()
                        .addComponent(qPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(entree_pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(accueilPanelLayout.createSequentialGroup()
                        .addGroup(accueilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bienvenue)
                            .addComponent(l_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(niveauPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        accueilPanelLayout.setVerticalGroup(
            accueilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accueilPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bienvenue)
                .addGroup(accueilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accueilPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(l_niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(accueilPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(niveauPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(accueilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entree_pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        nom.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nom.setText("Thibault MAITRE & Laure MUTHELET");

        projet.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        projet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projet.setText("Classe H P2025 *Projet CPO*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projet)
                        .addGap(325, 325, 325)
                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(accueilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_debut_jeu, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(accueilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_debut_jeu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entree_pseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree_pseudoActionPerformed
        // TODO add your handling code here:
        // on récupère les informations du joueur
        String pseudo=entree_pseudo.getText();
        joueur.setScore(0);
        joueur=new Joueur(pseudo,joueur.getScore(),date,niveau);
        b_debut_jeu.setEnabled(true);
    }//GEN-LAST:event_entree_pseudoActionPerformed

    private void b_debut_jeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_debut_jeuActionPerformed
        // TODO add your handling code here:
        if(b_facile.isSelected()){ // le joueur choisit le niveau facile
            n=0;
            niveau="Facile";
        }
        if(b_moyen.isSelected()){ // le joueur choisit le niveau moyen
            n=1;
            niveau="Moyen";
        }
        if(b_difficile.isSelected()){ // le joueur choisit le niveau difficile
            n=2;
            niveau="Difficile";  
        }
        this.setVisible(false); // une fois qu'on a cliqué sur le bouton, la page d'accueil disparaît
        page_jeu.setVisible(true); // une fois qu'on a cliqué sur le bouton, la page de jeu se lance
        page_jeu.init(); // on initialise le joueur avec son pseudo et son score
        // on assigne le niveau au joueur afin qu'il puisse être répertorié dans le tableau des scores dans la page meilleurs_scores
        joueur.setNiveau(niveau);
    }//GEN-LAST:event_b_debut_jeuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page_accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page_accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page_accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page_accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                new Page_accueil().setVisible(true);
                }
                catch(IOException exe){
                    
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accueilPanel;
    private javax.swing.JButton b_debut_jeu;
    private javax.swing.JRadioButton b_difficile;
    private javax.swing.JRadioButton b_facile;
    private javax.swing.JRadioButton b_moyen;
    private javax.swing.ButtonGroup b_niveau;
    private javax.swing.JLabel bienvenue;
    private javax.swing.JTextField entree_pseudo;
    private javax.swing.JLabel l_niveau;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel niveauPanel;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel projet;
    private javax.swing.JLabel qPseudo;
    // End of variables declaration//GEN-END:variables
}
